FROM centos:7

RUN yum -y update; yum -y install wget; \
    wget https://dist.ipfs.io/go-ipfs/v0.12.2/go-ipfs_v0.12.2_linux-amd64.tar.gz; \
    tar -xvzf go-ipfs_v0.12.2_linux-amd64.tar.gz; \
    cd go-ipfs; \
    ./install.sh



